"""review model make comment field nullable'

Revision ID: 547567b0b056
Revises: 6ec6c66ae6b7
Create Date: 2025-09-30 13:27:41.005836

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '547567b0b056'
down_revision: Union[str, Sequence[str], None] = '6ec6c66ae6b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reviews', 'comment',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reviews', 'comment',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
