name: fastapi-ecommerce-prod
services:
  web:
    build:
      context: .
      dockerfile: ./app/Dockerfile.prod
    command: gunicorn app.main:app --workers 4 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:8000
    # ports:
    #   - 8000:8000
    depends_on:
      - db

  db:
    image: postgres:17
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=ecommerce_user
      - POSTGRES_PASSWORD=12345678
      - POSTGRES_DB=ecommerce_db

  nginx:
    build: nginx
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    ports:
      - 80:80
      - 443:443
    depends_on:
      - web

  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    command: certonly --webroot --webroot-path=/var/www/certbot/ --email rgcs.rgcs@gmail.com --agree-tos --no-eff-email -d alshansky-g.ru
    depends_on:
      - nginx

volumes:
  postgres_data:
